/**
 * @file app shell mutation types
 * @author huanghuiquan(huanghuiquanhhh@gmail.com)
 */

export const ENABLE_PAGE_TRANSITION = 'ENABLE_PAGE_TRANSITION';
export const DISABLE_PAGE_TRANSITION = 'DISABLE_PAGE_TRANSITION';
export const SET_PAGE_SWITCHING = 'SET_PAGE_SWITCHING';
export const SET_PAGE_TRANSITION_NAME = 'SET_PAGE_TRANSITION_NAME';
export const SET_APP_HEADER = 'SET_APP_HEADER';
export const SET_APP_BOTTOM_NAV = 'SET_APP_BOTTOM_NAV';
export const ACTIVATE_APP_BOTTOM_NAV = 'ACTIVATE_APP_BOTTOM_NAV';
export const SET_SIDEBAR_VISIBILITY = 'SET_SIDEBAR_VISIBILITY';
export const SAVE_SCROLLTOP = 'SAVE_SCROLLTOP';

// home
export const SET_NEWS_DATA = 'SET_NEWS_DATA';
export const SET_LIST_FROM_CACHE = 'SET_LIST_FROM_CACHE';
export const SET_NEWS_LIST = 'SET_NEWS_LIST';
export const SET_NEWS_CATEGORY = 'SET_NEWS_CATEGORY';
export const SET_NEWS_ACTIVE_TAB = 'SET_NEWS_ACTIVE_TAB';
export const SET_NEWS_DETAIL = 'SET_NEWS_DETAIL';
export const SET_NEWS_FAVOR_LIST = 'SET_NEWS_FAVOR_LIST';
export const SET_NEWS_DETAIL_FAVOR_STATUS = 'SET_NEWS_DETAIL_FAVOR_STATUS';
export const ADD_QUERY_HISTORY = 'ADD_QUERY_HISTORY';
export const DELETE_QUERY_HISTORY = 'DELETE_QUERY_HISTORY';
export const SET_QUERY_RESULT = 'SET_QUERY_RESULT';
export const SET_PREVIEW_DATA = 'SET_PREVIEW_DATA';
export const DEL_CATEGORY = 'DEL_CATEGORY';
export const ADD_CATEGORY = 'ADD_CATEGORY';
